### ISSUE TITLE
Wildcard matching callbacks

### ISSUE THREAD

**Issue by CY-ipercept** [RenaudLN/dash-pydantic-form#12]
Hi again, I have a use case where I want to access the form by matching callback. I have multiple different types of object, each with their own prefilled form.
However, I see that the only support for this is to use the pydantic form ids.form_dependent_id

Is there a way to not use this, as this would require me to change all other callbacks to use this id type.
![image](https://github.com/RenaudLN/dash-pydantic-form/assets/143199677/2abb01a6-627c-41ac-a33a-eca7dc7a4906)

**Comment by RenaudLN** [comment]
You would need to use the same keys to match the form so matches would need to be on `aio_id` and `form_id` there's no other way I think as a bunch of callbacks rely on these keys in the matching internally.

**Comment by RenaudLN** [comment]
You would need to use the same keys to match the form so matches would need to be on `aio_id` and `form_id` there's no other way I think as a bunch of callbacks rely on these keys in the matching internally.

**Comment by CY-ipercept** [comment]
ah ok thank you!
