### ISSUE TITLE
Missing field from form data

### ISSUE THREAD

**Issue by CY-ipercept** [RenaudLN/dash-pydantic-form#16]
Hi @RenaudLN 

When i try to fetch the form data via a callback, i realise there is a missing field. 

I have verified that the item being passed into the form contains that field. However, when fetching data from this form, the entire field is missing. It might be due to the complex nature of the type of this field.

![image](https://github.com/RenaudLN/dash-pydantic-form/assets/143199677/284013bf-0c5f-471d-8c6a-4b5700e6a3fd)
![image](https://github.com/RenaudLN/dash-pydantic-form/assets/143199677/179469ba-3fd7-465c-9e7e-c2f1774151ec)
The values of the key value pair is a union of 2 different base models

The entire field is missing when it should show 
```
sensors: {
    "ACC": {
        ....
    },
    "CBM": {
        ....
    },
}
```

Update: i realise this happens only when i set the sensors field to read_only: True. I did this because it showed up as an object, which isn't helpful to users. 
![image](https://github.com/RenaudLN/dash-pydantic-form/assets/143199677/24d38f66-8c57-4237-a740-d535c6037f13)

**Comment by RenaudLN** [comment]
If you know exactly what keys should be there I would recommend changing the model to use them explicitly. Maybe something like

```py
class Sensors(BaseModel):
    ACC: ACCSensorData | None
    IMU: ACCSensorData | None
    # ...
    CBM: CBMSensorData | None
```

Or maybe have a list of ACCSensorData and list of CBMSensorData where each one has a sensor_name field.

**Comment by CY-ipercept** [comment]
ah i see, thanks for the help!
