### ISSUE TITLE
TextInput <input type="email">

### ISSUE THREAD

**Issue by Lxstr** [RenaudLN/dash-pydantic-form#27]
Hi there

Is there any way to pass type="email" to the TextInput for better browser autofill? This is set by default on the password field.

<input type="email">
[https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email)

Doesn't work
```
ModelForm(LoginData, "login", "auto", submit_on_enter=True, fields_repr={
                            "email": fields.Text(input_kwargs={"type": "email}),"password": fields.Password()
                        }),
```

Thanks

**Comment by RenaudLN** [comment]
It doesn't look like Mantine (and by extension DMC) has anything to set type=email on the TextInput unfortunately https://mantine.dev/core/text-input/?t=props

2 workarounds I can see:
* Create your own field with a dcc.Input which I believe supports type="email", but it makes it harder to get mantine-type styling
* Use a client side callback to set the type on the input, but that's a bit manual

**Comment by Lxstr** [comment]
OK thanks, will close this and open something in mantine
