### ISSUE TITLE
Change validation message

### ISSUE THREAD

**Issue by Lxstr** [RenaudLN/dash-pydantic-form#28]
![CleanShot 2024-09-29 at 23 46 28@2x](https://github.com/user-attachments/assets/b31524cb-0750-4873-aca1-5f2db4b9f62a)

Is there any way to change this message, may be confusing for users

**Comment by RenaudLN** [comment]
You can pass whatever you want to the error messages, don't have to output the pydantic validation error exactly, this was just an example.

**Comment by Lxstr** [comment]
Hi @RenaudLN 

Sorry I am struggling with exactly how to do this, any guidance would be great, first time with pydantic.

Just want to say "Invalid email" instead of "String should match pattern.."

Have tried both model_validator and field_validator, but nothing happens and in the model_validator, there are no messages.

```
class LoginData(BaseModel):
    email: str = Field(
        title="Email",
        pattern=email_regex,
    )
    password: str = Field(
        title="Password",
        min_length=6,
    )

    @field_validator("email")
    @classmethod
    def validate_x(cls, v: str) -> str:
        if not re.match(email_regex, v):
            raise ValueError("Custom error: Invalid email format.")
        return v

    @model_validator(mode="before")
    @classmethod
    def validate_email(cls, data: Any) -> Any:
        if not re.match(email_regex, data.get("email")):
            raise ValueError("Custom error: Invalid email format.")
        return data
```

**Comment by RenaudLN** [comment]
I assume you're using the example in usage.py, you can change the message that is surfaced here

```py
errors = {SEP.join([str(x) for x in error["loc"]]): error["msg"] for error in e.errors()}
#                                                                       ^ This here comes from pydantic validation
# You could do something like:
errors = {SEP.join([str(x) for x in error["loc"]]): f"Invalid {error['loc'][-1]}" for error in e.errors()}
```

**Comment by Lxstr** [comment]
Awesome thank you!
