### ISSUE TITLE
Pattern matching

### ISSUE THREAD

**Issue by mvheimburg** [RenaudLN/dash-pydantic-form#43]
Would be really nice to be able to use this in together with pattern matching callbacks.

eg:
Input(ModelForm.ids.main("FORM_ID", MATCH), "data")

**Comment by RenaudLN** [comment]
dash-pydantic-form uses a bunch of pattern matching callbacks under the hood so the id shape is relatively rigid. You can pattern match on `aio_id` and `form_id` but it means your other components also need one of these keys in their id.
