### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by maxschulz-COL** [RenaudLN/dash-pydantic-form#5]
Just wanted to ask if there were plans to add a `LICENSE.txt` :) ?

**Comment by RenaudLN** [comment]
Good catch, added an MIT license :+1:

**Comment by ctdunc** [comment]
Just to clarify -- the LICENSE field in `pyproject.toml` reads "Copyright ENEA Australia Pty Ltd - All Rights Reserved. Proprietary and confidential". 
Is this an oversight, or intentional? As I would imagine this overrides MIT + I would like to use this in a work project. 

Thanks

**Comment by RenaudLN** [comment]
Definitely an oversight, thanks for pointing it out, it's been fixed!

**Comment by Lucas-Steinmann** [comment]
I just saw in the MIT License:

https://github.com/RenaudLN/dash-pydantic-form/blob/bbbc8d0c91682487edac1e965fcc7a7f5f49d091/LICENSE#L3

I did not see how this is affiliated with Plotly and thought this might be a copy-paste error.
If not, sorry for the noise.

Anyway, cool project!

**Comment by RenaudLN** [comment]
Oops, good catch
