### ISSUE TITLE
Form columns are not passed properly to Modal renders

### ISSUE THREAD

**Issue by RenaudLN** [RenaudLN/dash-pydantic-form#52]

**Comment by sssaha** [comment]
Sorry somehow I was not able to post it on day - the later I resolved. However one thing - it seems like pydantic wants the full date and time for a date object which is represented by `fields.Datetime` - currently I am using Skipvalidation for that one - Any other solution or way of defining?

**Comment by sssaha** [comment]
@RenaudLN  - are you open to pull requests? I am adding features for my use case that I think can be beneficial

**Comment by RenaudLN** [comment]
Hey @sssaha I'm open to contributions but would prefer that you first open an issue related to what they're solving so we can discuss the approach first :)
