### ISSUE TITLE
List[str] or List[int] not rendering

### ISSUE THREAD

**Issue by anchengyang** [RenaudLN/dash-pydantic-form#6]
Thanks for putting up such a great module! Really excited to integrate it into my current dash application.

I have a question about BaseModels with fields of type List[str] and List[int]. 
I'm not sure how it works, why does a list of BaseModels render differently from a list of Python native types like int and str?

This is 
```
from typing import List
from pydantic import BaseModel, Field, ValidationError

class Employee(BaseModel):
      name: str = Field(title="Name", description="Name of the employee", min_length=2)
      age: int = Field(title="Age", description="Age of the employee, starting from their birth", ge=18)
      mini_bio: str | None = Field(title="Mini bio", description="Short bio of the employee", default=None)
      joined: date = Field(title="Joined", description="Date when the employee joined the company")
      office: Office = Field(title="Office", description="Office of the employee")
      metadata: Metadata | None = Field(title="Employee metadata", default=None)
      location: HomeOffice | WorkOffice | None = Field(title="Work location", default=None, discriminator="type")
      pets: list[Pet] = Field(title="Pets", description="Employee pets", default_factory=list)
      jobs: list[str] = Field(title="Jobs", description="Employee jobs", default_factory=list)
      cycleTracking: List[CycleSequence]
```
![image](https://github.com/RenaudLN/dash-pydantic-form/assets/65301406/9b50a1bf-b00d-4f0f-a229-273f178cbb9b)
![image](https://github.com/RenaudLN/dash-pydantic-form/assets/65301406/26d30781-6d6e-4d93-a88e-a3226dc59085)

Another question is, why is there a need to include Field object in the Jobs field? Leaving it as jobs: list[str] throws some error.
![image](https://github.com/RenaudLN/dash-pydantic-form/assets/65301406/7429ede3-779d-424a-8eb2-65c1d2569c58)

**Comment by RenaudLN** [comment]
Hi @anchengyang, at the moment there is no 'good' way to render lists of Python native objects but it could definitely be done in a similar fashion to the Model list. The difference between the 2 is that the Model list can leverage ModelForm recursively to render the sub-items but it's not currently supporting scalars.

This has given me an idea on how to do it easily so will let you know when there's progress.

Regarding the errors you are getting I will have a look, it looks like some thing(s) is(are) not handling well the null or undefined values on the javascript side.

**Comment by anchengyang** [comment]
ah i see, I was trying to trace the source code, and there is a function called `Type.classify()` that identifies `list<int>` as a SCALAR_LIST and returns `Type.SCALAR_LIST`. But I didn't manage to find where that value was returned to. Appreciate your help :)

**Comment by RenaudLN** [comment]
Should be working in 0.1.14 🙂 
![pydf-scalar-list](https://github.com/RenaudLN/dash-pydantic-form/assets/20662281/504bb992-8f71-49f7-a6fa-c845ee8027be)

**Comment by anchengyang** [comment]
Thank you so much for the quick response! This will be such a big help for me without having to change our existing Model!

**Comment by RenaudLN** [comment]
Should be available on pip now 👍
